server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    location / {
        # 写绝对路径
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 添加这行，对 SPA 应用很重要
        try_files $uri $uri/ /index.html;
    }
    # 后端接口代理改成 backend-svice
    location /api/ {
        proxy_pass http://backend-service.k8sdemon.svc.cluster.local:8080/;
    }
        
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}